package telasPessoa;

import controle.EstadoDAO;
import controle.InteresseControle;
import controle.PessoaControle;
import java.awt.PopupMenu;
import java.util.List;
import javax.persistence.EntityManager;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import modelo.Cidade;
import modelo.Estado;
import modelo.Interesse;
import modelo.Pessoa;
import util.JPAUtil;

public class TelaPessoaCadastrar extends javax.swing.JFrame {

    /**
     * Creates new form TelaPessoaCadastrar
     */
    Pessoa pessoa;
    private DefaultListModel lista= new DefaultListModel();
    
    public TelaPessoaCadastrar() {
        initComponents();
        carregarComboEstado();
        carregarComboInteresse();
    }
    
    private void preencherObjeto()  {
      
        pessoa.setNome(campoNome.getText());
        pessoa.setEndereco(campoEndereco.getText());
        pessoa.setTelefone(campoTelefone.getText());
        pessoa.setCidade((Cidade) comboCidade.getSelectedItem());
        JOptionPane.showMessageDialog(null,TelaInteresses.interesse.toString());
        pessoa.setInteresses(TelaInteresses.interesse);
    }
    private void preencherObjetoList(){
        //jListInteresse.removeAll();
       // lista.addElement(comboInteresse.getSelectedItem());
       // jListInteresse.setModel(lista);
    }
    private void carregarComboEstado()    {
        try {
            EntityManager em = JPAUtil.getJPAUtil();
            EstadoDAO dao = new EstadoDAO(em);
            List<Estado> estados = dao.listar();
            em.getTransaction().begin();
            comboEstado.removeAllItems();
            comboEstado.addItem(" ");
            for (Estado estado : estados) {
                comboEstado.addItem(estado);
            }
            em.getTransaction().commit();
            em.clear();
            em.close();
        } catch (ConstraintViolationException ex) {
            for (ConstraintViolation c : ex.getConstraintViolations()) {
                JOptionPane.showMessageDialog(null, c.getMessage());
            }
        }
    }
    
    private void carregarComboCidade()    {
        try {
            EntityManager em = JPAUtil.getJPAUtil();
            EstadoDAO dao = new EstadoDAO(em);
            List<Cidade> cidades = dao.getTodasCidadesEstado((Estado) comboEstado.getSelectedItem());
            em.getTransaction().begin();
            comboCidade.removeAllItems();
            for (Cidade cidade : cidades) {
                comboCidade.addItem(cidade);
            }
            em.getTransaction().commit();
            em.clear();
            em.close();
        } catch (ConstraintViolationException ex) {
            for (ConstraintViolation c : ex.getConstraintViolations()) {
                JOptionPane.showMessageDialog(null, c.getMessage());
            }
        }
    }
    
    
     private void carregarComboInteresse()    {
        try {
            EntityManager em = JPAUtil.getJPAUtil();
            InteresseControle dao = new InteresseControle(em);
            List<Interesse> interesses = dao.listar();
            em.getTransaction().begin();
           // comboInteresse.removeAllItems();
            //comboInteresse.addItem(" ");
            for (Interesse interesse : interesses) {
                //comboInteresse.addItem(interesse.getTipo());
            }
            em.getTransaction().commit();
            em.clear();
            em.close();
        } catch (ConstraintViolationException ex) {
            for (ConstraintViolation c : ex.getConstraintViolations()) {
                JOptionPane.showMessageDialog(null, c.getMessage());
            }
        }
    }
    private void limpar()   {
        campoNome.setText(null);
        campoEndereco.setText(null);
        campoTelefone.setText(null);
        comboCidade.setSelectedItem(null);
    }
    
    private void salvar()   {
        try {
            PessoaControle controle = new PessoaControle();
            pessoa = new Pessoa();
            preencherObjeto();
            controle.inserir(pessoa);
            JOptionPane.showMessageDialog(null, "Operação Realizada com Sucesso !!!");
        } catch (ConstraintViolationException cex) {
            for (ConstraintViolation c : cex.getConstraintViolations()) {
                JOptionPane.showMessageDialog(null, c.getMessage());
            }
            campoNome.setFocusable(true);
        }        
    }

    private void removeList(){
        
       // int index=jListInteresse.getSelectedIndex();
        //lista.remove(index);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jProgressBar1 = new javax.swing.JProgressBar();
        jPanel1 = new javax.swing.JPanel();
        rotuloNome = new javax.swing.JLabel();
        campoNome = new javax.swing.JTextField();
        botaoSalvar = new javax.swing.JButton();
        botaoCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        campoTelefone = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        campoEndereco = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        comboCidade = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        comboEstado = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela Cadastrar Pessoa");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Dados"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rotuloNome.setText("Nome:");
        jPanel1.add(rotuloNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));
        jPanel1.add(campoNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 300, -1));

        botaoSalvar.setText("Salvar");
        botaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarActionPerformed(evt);
            }
        });
        jPanel1.add(botaoSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, -1));

        botaoCancelar.setText("Cancelar");
        botaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(botaoCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, -1, -1));

        jLabel1.setText("Endereço:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        try {
            campoTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campoTelefone.setText("(  )      -     ");
        campoTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTelefoneActionPerformed(evt);
            }
        });
        jPanel1.add(campoTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 300, -1));

        jLabel2.setText("Telefone:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));
        jPanel1.add(campoEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 300, -1));

        jLabel3.setText("Cidade:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        comboCidade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboCidadeMouseClicked(evt);
            }
        });
        jPanel1.add(comboCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 300, -1));

        jLabel4.setText("Estado:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jPanel1.add(comboEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 300, -1));

        jButton1.setText("Iteresses");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 440));

        setSize(new java.awt.Dimension(413, 479));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_botaoCancelarActionPerformed

    private void botaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarActionPerformed
        salvar();
        limpar();
        campoNome.setFocusable(true);
    }//GEN-LAST:event_botaoSalvarActionPerformed

    private void campoTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTelefoneActionPerformed

    }//GEN-LAST:event_campoTelefoneActionPerformed

    private void comboCidadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboCidadeMouseClicked
        carregarComboCidade();
    }//GEN-LAST:event_comboCidadeMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        TelaInteresses inte = new TelaInteresses();
        inte.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPessoaCadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPessoaCadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPessoaCadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPessoaCadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPessoaCadastrar().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCancelar;
    private javax.swing.JButton botaoSalvar;
    private javax.swing.JTextField campoEndereco;
    private javax.swing.JTextField campoNome;
    private javax.swing.JFormattedTextField campoTelefone;
    private javax.swing.JComboBox comboCidade;
    private javax.swing.JComboBox comboEstado;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel rotuloNome;
    // End of variables declaration//GEN-END:variables
}
