package telasPessoa;

import controle.PessoaControle;
import controle.PessoaDAO;
import modelo.Pessoa;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.EntityManager;
import javax.swing.JOptionPane;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import modeloTabela.PessoaModeloTabela;
import util.JPAUtil;

public class TelaPessoaPesquisar extends javax.swing.JFrame {

    /**
     * Creates new form TelaPessoaPesquisar
     */
    
    List<Pessoa> pessoas = new ArrayList();
    Pessoa pessoa = new Pessoa();
    
    public TelaPessoaPesquisar() {
        initComponents();
        listar();
    }
    
    
    
    private void preencharTabela()   {
        PessoaModeloTabela pessoaModelo = new PessoaModeloTabela(pessoas);
        tabelaPessoa.setModel(pessoaModelo);
    }
  
       
    private void listar() {
        EntityManager em = JPAUtil.getJPAUtil();
        PessoaControle controle = new PessoaControle();
        PessoaDAO daoP = new PessoaDAO(em);
        pegarPesquisa();
        rotuloMedia.setText(String.valueOf(daoP.calcularMedia(this.pessoa)));
        try {
            pessoas = controle.getPessoas(this.pessoa);
            preencharTabela();
        } catch (ConstraintViolationException cex) {
            for (ConstraintViolation c : cex.getConstraintViolations()) {
                JOptionPane.showMessageDialog(null, c.getMessage());
            }
        }

    }
    private void pegarPesquisa(){
        this.pessoa.setNome(campoPequisa.getText());
    }
     
    private void visualizar() {
        PessoaControle controle = new PessoaControle();
        try {
            pessoa = controle.visualizar(pessoas.get(tabelaPessoa.getSelectedRow()));
        } catch (ConstraintViolationException cex) {
            for (ConstraintViolation c : cex.getConstraintViolations()) {
                JOptionPane.showMessageDialog(null, c.getMessage());
            }
        }
    }

    /**
     * This method is called from within ;the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaPessoa = new javax.swing.JTable();
        botaoCadastrar = new javax.swing.JButton();
        botaoVisualizar = new javax.swing.JButton();
        botaoCancelar = new javax.swing.JButton();
        botaoDuplicar = new javax.swing.JButton();
        rotuloMedia = new javax.swing.JLabel();
        campoPequisa = new javax.swing.JTextField();
        btnPesquisa = new javax.swing.JButton();
        asc = new javax.swing.JRadioButton();
        desc = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela Pesquisar Pessoa");
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Resultados Encontrados"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelaPessoa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nome", "Endereço", "Telefone", "Cidade", "Estado"
            }
        ));
        jScrollPane1.setViewportView(tabelaPessoa);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 570, 190));

        botaoCadastrar.setText("Cadastrar");
        botaoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarActionPerformed(evt);
            }
        });
        jPanel2.add(botaoCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        botaoVisualizar.setText("Visualizar");
        botaoVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVisualizarActionPerformed(evt);
            }
        });
        jPanel2.add(botaoVisualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));

        botaoCancelar.setText("Cancelar");
        botaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(botaoCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 220, -1, -1));

        botaoDuplicar.setText("Duplicar");
        botaoDuplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDuplicarActionPerformed(evt);
            }
        });
        jPanel2.add(botaoDuplicar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, -1, -1));

        rotuloMedia.setText("jLabel1");
        jPanel2.add(rotuloMedia, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 590, 260));
        getContentPane().add(campoPequisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 9, 520, 30));

        btnPesquisa.setText("OK");
        btnPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaActionPerformed(evt);
            }
        });
        getContentPane().add(btnPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 50, 30));

        buttonGroup1.add(asc);
        asc.setText("Crescente");
        asc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ascMouseClicked(evt);
            }
        });
        asc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ascActionPerformed(evt);
            }
        });
        getContentPane().add(asc, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, -1, -1));

        buttonGroup1.add(desc);
        desc.setText("Desc");
        desc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                descMouseClicked(evt);
            }
        });
        desc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descActionPerformed(evt);
            }
        });
        getContentPane().add(desc, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, -1, -1));

        setSize(new java.awt.Dimension(609, 383));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarActionPerformed
        System.exit(0);
        JPAUtil.fecharFabrica();
    }//GEN-LAST:event_botaoCancelarActionPerformed

    private void botaoVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVisualizarActionPerformed
        visualizar();
        TelaPessoaVisualizar tela = new TelaPessoaVisualizar(pessoa);
        tela.setVisible(true);
    }//GEN-LAST:event_botaoVisualizarActionPerformed

    private void botaoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarActionPerformed
        TelaPessoaCadastrar tela = new TelaPessoaCadastrar();
        tela.setVisible(true);
    }//GEN-LAST:event_botaoCadastrarActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown

    }//GEN-LAST:event_formComponentShown

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        listar();
    }//GEN-LAST:event_formWindowActivated

    private void botaoDuplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDuplicarActionPerformed
        // TODO add your handling code here:
         PessoaControle controle = new PessoaControle();
         List<Pessoa> pessoasAux = new ArrayList<>();
         
        try {
            EntityManager em = JPAUtil.getJPAUtil();
            Pessoa pessoaDouble = pessoas.get(tabelaPessoa.getSelectedRow());
            Pessoa pessoaAux = em.find(Pessoa.class, pessoaDouble.getId());
            pessoasAux = controle.listar();
            em.getTransaction().begin();
            em.detach(pessoaAux);
            Pessoa p1 = pessoaAux;
            p1.setId(pessoasAux.get(pessoasAux.size()-1).getId()+1);
            controle.alterar(p1);
            em.getTransaction().commit();
            em.close();
            JOptionPane.showMessageDialog(null, "pessoa duplicada");
            // controle.inserir(pessoaDouble);
            preencharTabela();
        } catch (ConstraintViolationException cex) {
            for (ConstraintViolation c : cex.getConstraintViolations()) {
                JOptionPane.showMessageDialog(null, c.getMessage());
            }
        }
    }//GEN-LAST:event_botaoDuplicarActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        preencharTabela();
    }//GEN-LAST:event_formWindowGainedFocus

    private void btnPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaActionPerformed
         listar();
    }//GEN-LAST:event_btnPesquisaActionPerformed

    private void ascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ascActionPerformed
        
    
    }//GEN-LAST:event_ascActionPerformed

    private void descActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descActionPerformed
       
    }//GEN-LAST:event_descActionPerformed

    private void descMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_descMouseClicked
        PessoaControle controle = new PessoaControle();
        pegarPesquisa();
        try {
            pessoas = controle.getPessoasDecrescente(pessoa);
            preencharTabela();
        } catch (ConstraintViolationException cex) {
            for (ConstraintViolation c : cex.getConstraintViolations()) {
                JOptionPane.showMessageDialog(null, c.getMessage());
            }
        }
    }//GEN-LAST:event_descMouseClicked

    private void ascMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ascMouseClicked
        PessoaControle controle = new PessoaControle();
        pegarPesquisa();
        try {
            pessoas = controle.getPessoasCrescente(pessoa);
            preencharTabela();
            repaint();
        } catch (ConstraintViolationException cex) {
            for (ConstraintViolation c : cex.getConstraintViolations()) {
                JOptionPane.showMessageDialog(null, c.getMessage());
            }
        }
    }//GEN-LAST:event_ascMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPessoaPesquisar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPessoaPesquisar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPessoaPesquisar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPessoaPesquisar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPessoaPesquisar().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton asc;
    private javax.swing.JButton botaoCadastrar;
    private javax.swing.JButton botaoCancelar;
    private javax.swing.JButton botaoDuplicar;
    private javax.swing.JButton botaoVisualizar;
    private javax.swing.JButton btnPesquisa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField campoPequisa;
    private javax.swing.JRadioButton desc;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel rotuloMedia;
    private javax.swing.JTable tabelaPessoa;
    // End of variables declaration//GEN-END:variables
}
